Integrate track picker
vgteam/sequenceTubeMap pull request #293
Opened 2023-06-14 05:20 UTC by ducku

Integrate track picker into the mounted files section

Notable Changes:
- The track data structure has been updated to support a single file rather than an array of files
- Tracks are stored in an object rather than an array, tracks are identified by an unique trackID

Bugs:
- Read coloring only partially works. Certain strands are not updated when the color changes.
- Region area does not display autocomplete until something has been typed

2023-06-14 14:22 UTC, adamnovak commented
> Region area does not display autocomplete until something has been typed

I don't think that's a new bug introduced here; I was seeing that as well without this PR; I've been having to hit the down arrow to pop it open.

2023-06-14 14:36 UTC, adamnovak requested changes
This looks pretty good!

I found some stuff that could be renamed/refactored, and I think I might have a vague lead on why the colors aren't applying right.

2023-06-14 14:36 UTC, adamnovak commented on src/App.js
> +function getColorSchemesFromTrack(tracks) {
This gets all the schemes form all the tracks, so it should probably be `getColorSchemesFromTracks` plural.

2023-06-14 14:36 UTC, adamnovak commented on src/Types.ts
>  }
Is this how you specify a dict from string to `track` in TypeScript syntax?

2023-06-14 14:36 UTC, adamnovak commented on src/Types.ts
> +}
Now we have duplicate copies of the type for the file.

We should probably get rid of `file`, and just have `track` have a filename string and a track type.

Or, we could store the type only in the file and not in the track.

But we should not store it twice.

2023-06-14 14:36 UTC, adamnovak commented on src/components/TubeMapContainer.js
> +
I think I moved this over to the `TubeMap` component; it looks like you are adding a new copy and not adding any calls to it.

Maybe something here is why the colors aren't applying properly?

2023-06-14 14:36 UTC, adamnovak commented on src/util/tubemap.js
> +  //console.log("source ID", track.sourceTrackID);
```suggestion
```

We should cut out this commented-out code.

2023-06-21 16:06 UTC, adamnovak commented
To put the log in a file you can do:
```
npm run test -- --watchAll=false test-names-if-you-want-any >log.txt 2>&1
```

2023-06-24 03:35 UTC, ducku commented
Bug:

When selecting a singular color from the color picker, not all reads are swapped to that color.

I've selected green as the read color on a singular read file, but some reads are still the default read color.
![image](https://github.com/vgteam/sequenceTubeMap/assets/23585956/d7cc7d62-3dd5-4dfa-995a-87bdb1b4cb41)

2023-06-26 15:29 UTC, adamnovak commented
It looks like the colors still don't update live, though the changes to the track design look good.

Do we want to change it to make people press the button to update the colors?

2023-06-28 17:06 UTC, adamnovak requested changes
This looks pretty good, although I think I found some dead code that ought to be cut. I will see if I can do that later today, or @ducku you can try to do it first.

2023-06-28 17:06 UTC, adamnovak commented on src/end-to-end.test.js
> +let dom;
Don't we not read this ever?

2023-07-03 15:28 UTC, adamnovak approved these changes

2023-07-03 15:32 UTC, merged