Extra Space Between Nodes
vgteam/sequenceTubeMap pull request #400
Opened 2024-03-10 23:39 UTC by ducku

Sometimes tracks don't have enough space to make a smooth transition from node to node. This PR creates extra space between nodes, taking into account the maximum difference in y values between nodes given any track. 

snp1kg-BRCA1
Before:
![snp1kg-BRCA1_before](https://github.com/vgteam/sequenceTubeMap/assets/23585956/2e81979a-9d0c-4a12-a574-85fd2dbdcab6)

After:
![snp1kg-BRCA1_after](https://github.com/vgteam/sequenceTubeMap/assets/23585956/73644e41-9d32-4ba5-93ec-2930f542d92f)

chr1_15608265_15608765
Before:
![chr1_15608265_15608765_before](https://github.com/vgteam/sequenceTubeMap/assets/23585956/240bf795-3f99-4121-9761-b55728891dc8)

After:
![chr1_15608265_15608765_after](https://github.com/vgteam/sequenceTubeMap/assets/23585956/42dc29e4-21cf-43b0-8c2f-d9269d83f33a)

2024-03-11 16:03 UTC, adamnovak commented
I like the space, but now it's easier to see that the reads are just sort of free-form swooshing around in these gaps, and their lines can get pretty thin along the axis perpendicular to their direction of motion. I wonder if there's a good way to use the extra space to ensure a minimum thickness or to get the reads to stick to horizontal and 45 degree angles.

2024-03-16 22:12 UTC, ducku commented
Currently, curves are drawn using SVG's Beziar Curves. We draw 2 parallel curves and fill them in.

Turns out, drawing [parallel Beziar Curves ](https://raphlinus.github.io/curves/2022/09/09/parallel-beziers.html)are pretty difficult. 

In commit 8b09fa2, some simple numbers were tweaked to make the curves look nicer.

In commit 14a46ec, I attempted to group sets of curves together and skew them based on how they're traversing. I think the results are better, but I'm not sure if it's the right way to do this. Maybe it's not a commit we want to keep.

snp1kg-BRCA1:
![Skewed_Beziar_snp1kg-BRCA1](https://github.com/vgteam/sequenceTubeMap/assets/23585956/e24f5ffd-3df3-4144-98cf-263a46ae6546)

ch1_15608265_15608765:
![Skewed_Beziar_ch1_15608265_15608765](https://github.com/vgteam/sequenceTubeMap/assets/23585956/7ff8a5f5-2a66-49e5-8a4b-15b9e969346c)

A low hanging fruit could be adding more space between nodes based on the number of curvy reads. 

Some improvements can also be made to how curves are grouped. Sometimes, curves start and end on the same node, but aren't neccesarily traversing together. Other times, curves start and end on different nodes, but are traversing closely together. In snp1kg-BRCA1, there's a single read going from T that gets covered up by the reads going from C. Them being grouped together can prevent the coverup.

2024-03-18 15:51 UTC, adamnovak requested changes
It looks like the reads do narrow less now. This might be as good as we can get without doing fancy curve fitting to find parallel curves, or using some other curve representation.

I have a couple comments on the code that I think should be addressed, but otherwise I think this is good.

We might want to add a checkbox in the visualization options accordion to remove the new horizontal space if someone wants a very compact view.

2024-03-18 15:51 UTC, adamnovak commented on src/util/tubemap.js
> +        // Track is going to a differnt node, account for space needed to limit rise/fall angle
```suggestion
        // Track is going to a different node; account for space needed to limit rise/fall angle 
```

2024-03-18 15:51 UTC, adamnovak commented on src/util/tubemap.js
>  function compareCurvesByLineChanges(a, b) {
This no longer compares by the number of vertical lanes changed, so I think it probably needs a different name now,

2024-03-20 14:33 UTC, adamnovak approved these changes

2024-03-20 14:33 UTC, merged